=== SushySan/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4de/Dieb.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Dieb" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Erster Eindruck"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Klettern"/>
		<OPTIONALTALENT name="Nahkampfwaffen"/>
		<OPTIONALTALENT name="Projektilwaffen"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Überraschungsschlag"/>
		<OPTIONALTALENT name="Verspotten"/>
		<OPTIONALTALENT name="Weitsprung"/>
		<OPTIONALTALENT name="Wurfwaffen"/>
		<FREETALENT name="Gefahrensinn"/>
		<DISCIPLINETALENT name="Aufmerksamkeit"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Diebweben"/>
		<DISCIPLINETALENT name="Heimlicher Schritt"/>
		<DISCIPLINETALENT name="Schloss Knacken"/>
		<DISCIPLINETALENT name="Taschendiebstahl"/>
		<TALENTABILITY/>
		<KARMA spend="Charismaproben beim Täuschen"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Fallen Entschärfen"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Feilschen"/>
		<TALENTABILITY/>
		<KARMA spend="Initiativeproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Gegenstand Verbergen"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Eleganter Abgang"/>
		<OPTIONALTALENT name="Klingen Jonglieren"/>
		<OPTIONALTALENT name="Mystische Verfolgung"/>
		<OPTIONALTALENT name="Magische Maske"/>
		<OPTIONALTALENT name="Projektil Rufen"/>
		<OPTIONALTALENT name="Schwachstelle Erkennen"/>
		<OPTIONALTALENT name="Stimmen Imitieren"/>
		<OPTIONALTALENT name="Totstellen"/>
		<OPTIONALTALENT name="Untrüglicher Blick"/>
		<OPTIONALTALENT name="Zweitwaffe"/>
		<DISCIPLINETALENT name="Wortgeplänkel"/>
		<TALENTABILITY/>
		<KARMA spend="Angriffsproben bei Überraschung oder Toter Winkel"/>
		<ABILITY>Schattenmantel</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Schuld Abwälzen"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Flinke Hand"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Illusionsverstärkung"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Akrobatische Verteidigung"/>
		<OPTIONALTALENT name="Astralsicht"/>
		<OPTIONALTALENT name="Echolot"/>
		<OPTIONALTALENT name="Fluchtplan"/>
		<OPTIONALTALENT name="Kampfsinn"/>
		<OPTIONALTALENT name="Kreisender Spion"/>
		<OPTIONALTALENT name="Perfekte Konzentration"/>
		<OPTIONALTALENT name="Starrsinn"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<OPTIONALTALENT name="Windkissen"/>
		<DISCIPLINETALENT name="Machtmaskierung"/>
		<TALENTABILITY/>
		<KARMA spend="Erholungsproben"/>
		<ABILITY>Schattensicht</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Astraltasche"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Chamäleon"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMA spend="Schadensproben gegen Ziele mit Malus auf körperlicher Verteidigung"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Täuschende Klinge"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Astralangriff"/>
		<OPTIONALTALENT name="Entwaffnendes Lächeln"/>
		<OPTIONALTALENT name="Fließende Bewegung"/>
		<OPTIONALTALENT name="Geistwandeln"/>
		<OPTIONALTALENT name="Kritischer Treffer"/>
		<OPTIONALTALENT name="Verteidigungshaltung"/>
		<OPTIONALTALENT name="Wie Eine Streunende Katze"/>
		<OPTIONALTALENT name="Zweite Chance"/>
		<DISCIPLINETALENT name="Unmögliches Versteck"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<ARMOR name="additional discipline bonus" weight="0" used="yes" location="self" mysticarmor="1"/>
		<KARMASTEP />
		<ABILITY>Eins mit dem Schatten</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Talentdiebstahl"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Traumdieb"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Diebe können Halbmagie einsetzen, um Sicherheitsmaßnahmen zu bauen oder zu umgehen, die Diebstähle verhindern sollen, und um verschiedene Arten von Schließmechanismen zu erkennen.</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4en/Boatman.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Boatman" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Defense"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Read River"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Taunt"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<FREETALENT name="Pilot Boat"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Climbing"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="River Weaving"/>
		<DISCIPLINETALENT name="Swimming"/>
		<TALENTABILITY/>
		<KARMA spend="once per round on any action taken while on board a riverboat"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Awareness"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Empathic Sense"/>
		<TALENTABILITY/>
		<KARMA spend="on Initiative tests"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Wound Balance"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Battle Bellow"/>
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Engaging Banter"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Second Weapon"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<DISCIPLINETALENT name="Heartening Laugh"/>
		<TALENTABILITY/>
		<KARMA spend="on Interaction Tests"/>
		<ABILITY>Collaborate</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Disarm"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Inspire Others"/>
		<TALENTABILITY/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Lion Heart"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>The Boatman sits alone in silent meditation preferably near a river or other body of water for several minutes, picturing in their mindâ€™s eye their riverboat cruising through the current at the start of a long journey. The adept envisions a journey they hope to make one day, imagining scenes of this journey, including the risks and perils, and how their training and skills might help make the journey a safe one. The ritual is complete when, half an hour later, the imagined journey ends safely.</KARMARITUAL>
	<HALFMAGIC>The Boatman uses Half-Magic for knowledge of riverboat designs, recognition of different types of riverboats, commonly river trade routes, and riverboat crew complements. It may also cover the maintenance, repair, and construction of riverboats (this does not include fire engines).</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4de/Kundschafter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Kundschafter" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Fallen Entschärfen"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Kampfsinn"/>
		<OPTIONALTALENT name="Lesen/Schreiben"/>
		<OPTIONALTALENT name="Nahkampfwaffen"/>
		<OPTIONALTALENT name="Projektilwaffen"/>
		<OPTIONALTALENT name="Schloss Knacken"/>
		<OPTIONALTALENT name="Tieranalyse"/>
		<OPTIONALTALENT name="Weitsprung"/>
		<FREETALENT name="Navigation"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Kundschafterweben"/>
		<DISCIPLINETALENT name="Aufmerksamkeit"/>
		<DISCIPLINETALENT name="Klettern"/>
		<DISCIPLINETALENT name="Spurenlesen"/>
		<DISCIPLINETALENT name="Wildnisüberleben"/>
		<TALENTABILITY/>
		<KARMA spend="Proben um etwas zu finden"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Heimlicher Schritt"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Mystische Verfolgung"/>
		<TALENTABILITY/>
		<KARMA spend="Initiativeproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Gefahrensinn"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Gegenstand Verbergen"/>
		<OPTIONALTALENT name="Geisterreittier"/>
		<OPTIONALTALENT name="Magische Maske"/>
		<OPTIONALTALENT name="Schwachstelle Erkennen"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Tierfreundschaft"/>
		<OPTIONALTALENT name="Tierische Sinne"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<OPTIONALTALENT name="Überraschungsschlag"/>
		<OPTIONALTALENT name="Untrüglicher Blick"/>
		<DISCIPLINETALENT name="Beweisanalyse"/>
		<TALENTABILITY/>
		<KARMA spend="Erholungsproben"/>
		<ABILITY>Geschärfte Sinne</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Astralsicht"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Sicherer Pfad"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Kreisender Spion"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Erkennt Spuren und Fährten von Tieren und Namensgebern in der Stadt und auf dem Land; Wissen über Pflanzen, Kreaturen und Kulturen in Barsaive</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4de/Schwertmeister.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Schwermeister" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="7" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Ablenken"/>
		<OPTIONALTALENT name="Akrobatische Verteidigung"/>
		<OPTIONALTALENT name="Beeindrucken"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Gefahrensinn"/>
		<OPTIONALTALENT name="Gewinnendes Lächeln"/>
		<OPTIONALTALENT name="Kampfsinn"/>
		<OPTIONALTALENT name="Standhaftigkeit"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<OPTIONALTALENT name="Waffenloser Kampf"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Waffenweben"/>
		<DISCIPLINETALENT name="Hieb Ausweichen"/>
		<DISCIPLINETALENT name="Manövrieren"/>
		<DISCIPLINETALENT name="Nahkampfwaffen"/>
		<DISCIPLINETALENT name="Verspotten"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Erster Eindruck"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Riposte"/>
		<TALENTABILITY/>
		<KARMA spend="Interaktionsproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Herzliches Lachen"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Bleibender Eindruck"/>
		<OPTIONALTALENT name="Eleganter Abgang"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Kobrastoß"/>
		<OPTIONALTALENT name="Löwenherz"/>
		<OPTIONALTALENT name="Luftgleiten"/>
		<OPTIONALTALENT name="Nachtreten"/>
		<OPTIONALTALENT name="Schwachstelle Erkennen"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Wortgeplänkel"/>
		<DISCIPLINETALENT name="Zweitwaffe"/>
		<TALENTABILITY/>
		<KARMA spend="Schadensproben mit einer Nahkampfwaffe"/>
		<ABILITY>Einschätzen</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Entwaffnen"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Starrsinn"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Zweiter Angriff"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Astralangriff"/>
		<OPTIONALTALENT name="Ätherwaffe"/>
		<OPTIONALTALENT name="Empathische Wahrnehmung"/>
		<OPTIONALTALENT name="Herausforderung der Besten"/>
		<OPTIONALTALENT name="Letzte Rettung"/>
		<OPTIONALTALENT name="Löwenmut"/>
		<OPTIONALTALENT name="Matrixsicht"/>
		<OPTIONALTALENT name="Schlagfertige Erwiderung"/>
		<OPTIONALTALENT name="Unaufhaltsame Erholung"/>
		<OPTIONALTALENT name="Untergraben"/>
		<DISCIPLINETALENT name="Kritischer Treffer"/>
		<TALENTABILITY/>
		<KARMA spend="Erholungsproben"/>
		<ABILITY>Blutgebunde Waffen</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Schwungvoller Angriff"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Schwungvoller Angriff"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMA spend="Angriff gegen verspottete Gegner"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Fließende Bewegung"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Aurarüstung"/>
		<OPTIONALTALENT name="Bardenstimme"/>
		<OPTIONALTALENT name="Eisiger Schlag"/>
		<OPTIONALTALENT name="Schmerzen Widerstehen"/>
		<OPTIONALTALENT name="Seelenschutz"/>
		<OPTIONALTALENT name="Unverzagte Tapferkeit"/>
		<OPTIONALTALENT name="Vitaler Schutz"/>
		<OPTIONALTALENT name="Zweite Chance"/>
		<DISCIPLINETALENT name="Schneidende Worte"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<ARMOR name="additional discipline bonus" weight="0" used="yes" location="self" mysticarmor="1"/>
		<KARMASTEP />
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Üble Wunde"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Mehrfacher Schlag"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min. </KARMARITUAL>
	<HALFMAGIC> Pflege ihrer Waffen; Wissen über: legendäre Waffen, Typen von Nahkampfwaffen; Erkennen von Schwertmeister Techniken und Kampfstile berühmter Schwertmeister</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Purifier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE  name="Purifier" lang="en" bookref="NG p.172" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="7" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Battle Shout"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Body Control"/>
		<DISCIPLINETALENT name="Clay Skin"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Wound Balance"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Tracking"/>
		<DISCIPLINETALENT name="Lifesight"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Spirit Talk"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Earth Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Strengh-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Earth Skin"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Steely Stare"/>
		<OPTIONALTALENT name="Temper Self"/>
		<DISCIPLINETALENT name="Earth Bond"/>
		<TALENTABILITY/>
		<ABILITY>Cleanse</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Life Check"/>
		<TALENTABILITY/>
		<KARMA spend="Toughness-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Crushing Blow"/>
		<TALENTABILITY/>
		<KARMA spend="unarmend Damage Tests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Momentum Attack"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Matrix Strike"/>
		<OPTIONALTALENT name="Metal Ward"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<DISCIPLINETALENT name="Safe Path"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Earth's Avenger</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Plant Shelter"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Vitality"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Earth Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Chameleon"/>
		<OPTIONALTALENT name="Detect Influence"/>
		<OPTIONALTALENT name="Moving Earth"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<OPTIONALTALENT name="Stone Skin"/>
		<OPTIONALTALENT name="Whirlwind"/>
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMASTEP/>
		<ABILITY>Sanctify</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Elemental Walk"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: all aspects of nature, preserving natural environs, all that tends to currupt nature (including Horrors, misdeeds of Namegiver civilization); Skill: Navigation, Wilderness Survival;(NG p.175)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/DaughterOfHeaven.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Daughter of Heaven" lang="en" bookref="CPG p.31" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Embrace of the Phoenix"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Lifesight"/>
		<DISCIPLINETALENT name="Wound Balance"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Close In"/>
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Missile Weapons"/>
		<OPTIONALTALENT name="Parry"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<DISCIPLINETALENT name="Fire Heal"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Improvised Poultice"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Thread Mending"/>
		<TALENTABILITY/>
		<KARMA spend="Toughness-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Diplomacy"/>
		<OPTIONALTALENT name="Disarm"/>
		<OPTIONALTALENT name="Empathic Sense"/>
		<OPTIONALTALENT name="Fireblood"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Sense Poison"/>
		<OPTIONALTALENT name="Shackle Shrug"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Gift of the Phoenix"/>
		<TALENTABILITY/>
		<ABILITY>Gift of heaven</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Counteract"/>
		<TALENTABILITY/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Life Check"/>
		<TALENTABILITY/>
		<KARMA spend="Test made by target to heal damage/ resist poison or disease. Adept has to be adjacent to target to grant Karma Point."/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Touch of the Phoenix"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Endure Cold"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Impressive Shot"/>
		<OPTIONALTALENT name="Impressive Strike"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Quick Shot"/>
		<OPTIONALTALENT name="Vitality"/>
		<DISCIPLINETALENT name="Shield of the Innocent"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Trust of the Phoenix</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Lion Spirit"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Cyclone"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
		<KARMA spend="reduce Current Damage of adjacent target by result (once per round)"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Path of the Righteous"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Confront Horror"/>
		<OPTIONALTALENT name="Detect Influence"/>
		<OPTIONALTALENT name="First Ring of Perfection"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Vital Strike"/>
		<OPTIONALTALENT name="Wound Transfer"/>
		<DISCIPLINETALENT name="Aura Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Grace of the Phoenix</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Purge Pattern"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: Namegiver physiology, illnesses, diseases, poisons and how to treat them, medicinal herbs and plants; craft simple healing aids (bandages, splints, etc.); Skill: Alchemy for Analysis/Gathering Ingredients requires produce improvised poultices; (CPG p.32)</HALFMAGIC>
</DISCIPLINE>
