=== SushySan/Earthdawn-Character-Editor/config/earthdawnnamegivers.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/namegiver" xmlns="http://earthdawn.com/namegiver" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:simpleType name="namegivermovmenttype_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ground"/>
			<xs:enumeration value="flight"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ATTRIBUTENAMEVALUE_type">
		<xs:attribute name="name" type="edt:ATTRIBUTE_name_type" use="required"/>
		<xs:attribute name="value" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAMEGIVERMOVEMENT_type">
		<xs:attribute name="type" type="namegivermovmenttype_type" use="required"/>
		<xs:attribute name="value" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAMEGIVERWEAPONSIZERESTRICTION_type">
		<xs:attribute name="onehandmin" type="edt:unsigned_int" default="1"/>
		<xs:attribute name="onehandmax" type="edt:unsigned_int" default="3"/>
		<xs:attribute name="twohandmin" type="edt:unsigned_int" default="4"/>
		<xs:attribute name="twohandmax" type="edt:unsigned_int" default="6"/>
	</xs:complexType>
	<xs:complexType name="NAMEGIVERABILITY_type">
		<xs:sequence>
			<xs:element maxOccurs="6" minOccurs="6" name="ATTRIBUTE" type="ATTRIBUTENAMEVALUE_type"/>
			<xs:element maxOccurs="1" minOccurs="1" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element maxOccurs="1" minOccurs="1" name="WOUND" type="edt:WOUND_type"/>
			<xs:element maxOccurs="1" minOccurs="1" name="WEAPONSIZERESTRICTION" type="NAMEGIVERWEAPONSIZERESTRICTION_type"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="TALENT" type="edt:TALENTABILITY_type"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="CARRY" type="edt:TALENTABILITY_type"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="ABILITY" type="xs:string"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="ORIGIN" type="xs:string"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="NOTDEFAULTSKILL" type="xs:string"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="DEFAULTLANGUAGE" type="edt:CHARACTERLANGUAGE_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="karmamodifier" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="movement_ground" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="movement_flight" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="enduringarmorfactor" type="xs:float" default="1.0"/>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
		<xs:attribute name="type" type="xs:string" default=""/>
	</xs:complexType>
	<xs:element name="NAMEGIVERS">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="NAMEGIVER" type="NAMEGIVERABILITY_type"/>
			</xs:sequence>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/namegivers/ED4de.xml
<?xml version="1.0" encoding="UTF-8" ?>
<NAMEGIVERS rulesetversion="ED4" xmlns="http://earthdawn.com/namegiver" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/namegiver ../earthdawnnamegivers.xsd">
	<NAMEGIVER lang="de" name="Elf" karmamodifier="4" movement_ground="14" type="Elf">
		<ATTRIBUTE name="DEX" value="12"/>
		<ATTRIBUTE name="STR" value="10"/>
		<ATTRIBUTE name="TOU" value="8"/>
		<ATTRIBUTE name="PER" value="11"/>
		<ATTRIBUTE name="WIL" value="11"/>
		<ATTRIBUTE name="CHA" value="11"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION/>
		<ABILITY>Nachtsicht</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="Sperethiel (Elfisch)" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Mensch" karmamodifier="5" movement_ground="12" type="Mensch">
		<ATTRIBUTE name="DEX" value="10"/>
		<ATTRIBUTE name="STR" value="10"/>
		<ATTRIBUTE name="TOU" value="10"/>
		<ATTRIBUTE name="PER" value="10"/>
		<ATTRIBUTE name="WIL" value="10"/>
		<ATTRIBUTE name="CHA" value="10"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION/>
		<TALENT name="Vielseitigkeit"/>
		<ABILITY>Vielseitigkeit</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<ORIGIN>Thera</ORIGIN>
		<DEFAULTLANGUAGE language="Menschlich" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Obsidianer" karmamodifier="3" movement_ground="10" enduringarmorfactor="0.8" type="Obsidianer">
		<ATTRIBUTE name="DEX" value="8"/>
		<ATTRIBUTE name="STR" value="18"/>
		<ATTRIBUTE name="TOU" value="13"/>
		<ATTRIBUTE name="PER" value="9"/>
		<ATTRIBUTE name="WIL" value="10"/>
		<ATTRIBUTE name="CHA" value="9"/>
		<ARMOR name="Natürliche Rüstung" weight="0" used="yes" location="selbst" physicalarmor="3"/>
		<WOUND threshold="3"/>
		<WEAPONSIZERESTRICTION onehandmin="2" onehandmax="4" twohandmin="5" twohandmax="7"/>
		<ABILITY>Natürliche Rüstung</ABILITY>
		<ABILITY>Erhöhte Wundschwelle</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="Obsidianisch" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Ork" karmamodifier="5" movement_ground="12" type="Ork">
		<ATTRIBUTE name="DEX" value="10"/>
		<ATTRIBUTE name="STR" value="13"/>
		<ATTRIBUTE name="TOU" value="11"/>
		<ATTRIBUTE name="PER" value="10"/>
		<ATTRIBUTE name="WIL" value="8"/>
		<ATTRIBUTE name="CHA" value="9"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION/>
		<ABILITY>Gahad</ABILITY>
		<ABILITY>Nachticht</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="Or'zet (Orkisch)" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Troll" karmamodifier="3" movement_ground="14" enduringarmorfactor="0.8" type="Troll">
		<ATTRIBUTE name="DEX" value="10"/>
		<ATTRIBUTE name="STR" value="14"/>
		<ATTRIBUTE name="TOU" value="12"/>
		<ATTRIBUTE name="PER" value="9"/>
		<ATTRIBUTE name="WIL" value="11"/>
		<ATTRIBUTE name="CHA" value="10"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION onehandmin="2" onehandmax="4" twohandmin="5" twohandmax="7"/>
		<ABILITY>Wärmesicht</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="Trollisch" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="T'skrang" karmamodifier="4" movement_ground="12" type="T'skrang">
		<ATTRIBUTE name="DEX" value="11"/>
		<ATTRIBUTE name="STR" value="10"/>
		<ATTRIBUTE name="TOU" value="11"/>
		<ATTRIBUTE name="PER" value="10"/>
		<ATTRIBUTE name="WIL" value="10"/>
		<ATTRIBUTE name="CHA" value="11"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION/>
		<ABILITY>Schwanzkampf</ABILITY>
		<ABILITY>Kiemen</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="T'Skrang" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Windling" karmamodifier="6" movement_ground="6" movement_flight="16" enduringarmorfactor="1.5" type="Windling">
		<ATTRIBUTE name="DEX" value="11"/>
		<ATTRIBUTE name="STR" value="4"/>
		<ATTRIBUTE name="TOU" value="8"/>
		<ATTRIBUTE name="PER" value="11"/>
		<ATTRIBUTE name="WIL" value="10"/>
		<ATTRIBUTE name="CHA" value="12"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION onehandmax="1" twohandmin="2" twohandmax="2"/>
		<DEFENSE kind="physical" bonus="2"/>
		<TALENT name="Astralsicht"/>
		<ABILITY>Flugfähigkeit</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<NOTDEFAULTSKILL>Schwimmen</NOTDEFAULTSKILL>
		<DEFAULTLANGUAGE language="Windling" speak="skill"/>
	</NAMEGIVER>
	<NAMEGIVER lang="de" name="Zwerg" karmamodifier="4" movement_ground="10" type="Zwerg">
		<ATTRIBUTE name="DEX" value="9"/>
		<ATTRIBUTE name="STR" value="10"/>
		<ATTRIBUTE name="TOU" value="12"/>
		<ATTRIBUTE name="PER" value="11"/>
		<ATTRIBUTE name="WIL" value="11"/>
		<ATTRIBUTE name="CHA" value="10"/>
		<ARMOR name="natürliche Rüstung" weight="0" used="yes" location="selbst"/>
		<WOUND threshold="0"/>
		<WEAPONSIZERESTRICTION twohandmax="5"/>
		<CARRY name="Starker Rücken" bonus="2"/>
		<ABILITY>Wärmesicht</ABILITY>
		<ABILITY>Starker Rücken</ABILITY>
		<ORIGIN>Barsaive</ORIGIN>
		<DEFAULTLANGUAGE language="Sprache nach Wahl" speak="skill"/>
	</NAMEGIVER>
</NAMEGIVERS>
