=== SushySan/Earthdawn-Character-Editor/config/earthdawnquestor.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="QUESTORRANK_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="1" maxOccurs="1" name="DEVOTIONABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEVOTIONDICESTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEVOTIONBENEFIT" type="edt:KARMAABILITY_type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QUESTORTIER_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALDEVOTION" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="15" name="RANK" type="QUESTORRANK_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="edt:tierkind_type" default="auto"/>
	</xs:complexType>
	<xs:element name="QUESTOR">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DEVOTION" type="edt:TALENTABILITY_type"/>
				<xs:element minOccurs="2" maxOccurs="4" name="TIER" type="QUESTORTIER_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="IDEAL" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="passion" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED4"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/questors/ED4de/Chorrolis.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QUESTOR passion="Chorrolis" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawnquestor.xsd">
	<DEVOTION name="Questor" limitation="Chorrolis"/>
	<TIER>
		<OPTIONALDEVOTION name="Bestechung"/>
		<OPTIONALDEVOTION name="Erster Eindruck"/>
		<OPTIONALDEVOTION name="Etikette"/>
		<OPTIONALDEVOTION name="Feilschen"/>
		<OPTIONALDEVOTION name="Gassenwissen"/>
		<OPTIONALDEVOTION name="Konversation"/>
		<OPTIONALDEVOTION name="Lippenlesen"/>
		<OPTIONALDEVOTION name="Pidginsprache"/>
		<OPTIONALDEVOTION name="Schätzen"/>
		<OPTIONALDEVOTION name="Stärkung der Passion"/>
		<RANK><!-- 1 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP count="3"/>
			<DEVOTIONBENEFIT spend="tbd by questor"/>
		</RANK>	
		<RANK><!-- 2 -->
			<DEVOTIONABILITY/>
		</RANK>	
		<RANK><!-- 3 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>	
		<RANK><!-- 4 -->
			<DEVOTIONABILITY/>
		</RANK>	
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Absichten Einschätzen"/>
		<OPTIONALDEVOTION name="Besessenheit Wecken"/>
		<OPTIONALDEVOTION name="Diplomatie"/>
		<OPTIONALDEVOTION name="Herzenswunsch"/>
		<OPTIONALDEVOTION name="Inspiration der Passion"/>
		<OPTIONALDEVOTION name="Psychometrie"/>
		<OPTIONALDEVOTION name="Starrsinn"/>
		<OPTIONALDEVOTION name="Untrüglicher Blick"/>
		<RANK><!-- 5 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>	
		<RANK><!-- 6 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>	
		<RANK><!-- 7 -->
			<DEVOTIONABILITY/>
			<ARMOR name="additional questor armor" mysticarmor="1" weight="0"/>
		</RANK>	
		<RANK><!-- 8 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>	
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Gedanken Verbergen"/>
		<OPTIONALDEVOTION name="Griff von Chorrolis"/>
		<OPTIONALDEVOTION name="Lass Uns Handeln"/>
		<OPTIONALDEVOTION name="Untergraben"/>
		<OPTIONALDEVOTION name="Vergangenheitsberührung"/>
		<OPTIONALDEVOTION name="Verzaubertes Geschenk"/>
		<RANK><!-- 9 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>	
		<RANK><!-- 10 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>	
		<RANK><!-- 11 -->
			<DEVOTIONABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>	
		<RANK><!-- 12 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
			<INITIATIVE/>
		</RANK>	
	</TIER>
	<IDEAL>Reichtum</IDEAL>
	<IDEAL>Handel</IDEAL>
	<IDEAL>Neid</IDEAL>
	<IDEAL>Verlangen</IDEAL>
	<!-- Der Questor kann einen Weihepunkt ausgeben für ... .-->
	<DEVOTIONBENEFITEXAMPLE>eine Interaktionsprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, bei der es um eine Transaktion geht</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um Informationen über die Wirtschaft zu erhalten, einschließlich neuer Handelswege, Rohstoffquellen, Suche nach einem bestimmten Handwerker usw.</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um etwas Wünschenswertes zu erwerben</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, die eine neue und riskante wirtschaftliche Unternehmung unterstützt</DEVOTIONBENEFITEXAMPLE>
</QUESTOR>

=== SushySan/Earthdawn-Character-Editor/config/questors/ED4de/Floranuus.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QUESTOR passion="Floranuus" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawnquestor.xsd">
	<DEVOTION name="Questor" limitation="Floranuus"/>
	<TIER>
		<OPTIONALDEVOTION name="Akrobatische Verteidigung"/>
		<OPTIONALDEVOTION name="Erster Eindruck"/>
		<OPTIONALDEVOTION name="Gewinnendes Lächeln"/>
		<OPTIONALDEVOTION name="Herzliches Lachen"/>
		<OPTIONALDEVOTION name="Hieb Ausweichen"/>
		<OPTIONALDEVOTION name="Sprint"/>
		<OPTIONALDEVOTION name="Stärkung der Passion"/>
		<OPTIONALDEVOTION name="Unempfindlichkeit" limitation="5"/>
		<OPTIONALDEVOTION name="Weitsprung"/>
		<OPTIONALDEVOTION name="Windkissen"/>
		<RANK><!-- 1 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP count="3"/>
			<DEVOTIONBENEFIT spend="tbd by questor"/>
		</RANK>	
		<RANK><!-- 2 -->
			<DEVOTIONABILITY/>
		</RANK>	
		<RANK><!-- 3 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>	
		<RANK><!-- 4 -->
			<DEVOTIONABILITY/>
		</RANK>	
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Ermutigende Redekunst"/>
		<OPTIONALDEVOTION name="Floranuus' Schritt"/>
		<OPTIONALDEVOTION name="Führung"/>
		<OPTIONALDEVOTION name="Geschichten Erzählen"/>
		<OPTIONALDEVOTION name="Inspiration der Passion"/>
		<OPTIONALDEVOTION name="Inspirierte Kraft"/>
		<OPTIONALDEVOTION name="Löwenherz"/>
		<OPTIONALDEVOTION name="Luftgleiten"/>
		<RANK><!-- 5 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>	
		<RANK><!-- 6 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>	
		<RANK><!-- 7 -->
			<DEVOTIONABILITY/>
			<INITIATIVE/>
		</RANK>	
		<RANK><!-- 8 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>	
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Ansporn"/>
		<OPTIONALDEVOTION name="Energie in Bewegung"/>
		<OPTIONALDEVOTION name="Geschenk des Lebens"/>
		<OPTIONALDEVOTION name="Inspirierte Ausdauer"/>
		<OPTIONALDEVOTION name="Stärkung"/>
		<OPTIONALDEVOTION name="Trost der Passion"/>
		<RANK><!-- 9 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>	
		<RANK><!-- 10 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>	
		<RANK><!-- 11 -->
			<DEVOTIONABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>	
		<RANK><!-- 12 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
			<INITIATIVE/>
		</RANK>	
	</TIER>
	<IDEAL>Festlichkeit</IDEAL>
	<IDEAL>Energie</IDEAL>
	<IDEAL>Sieg</IDEAL>
	<IDEAL>Bewegung</IDEAL>
	<!-- Der Questor kann einen Weihepunkt ausgeben für ... .-->
	<DEVOTIONBENEFITEXAMPLE>die nächste Aktionsprobe eines Verbündeten nach einer erfolgreichen Aktionsprobe eines anderen Verbündeten</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Erholungsprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Initiativeprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Interaktionsprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, bei der es um Athletik geht (gilt nicht für Angriffs- oder Schadensproben)</DEVOTIONBENEFITEXAMPLE>
</QUESTOR>

=== SushySan/Earthdawn-Character-Editor/config/questors/ED4de/Astendar.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QUESTOR passion="Astendar" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawnquestor.xsd">
	<DEVOTION name="Questor" limitation="Astendar"/>
	<TIER>
		<OPTIONALDEVOTION name="Beeindrucken"/>
		<OPTIONALDEVOTION name="Bildende Kunst"/>
		<OPTIONALDEVOTION name="Empathische Wahrnehmung"/>
		<OPTIONALDEVOTION name="Erster Eindruck"/>
		<OPTIONALDEVOTION name="Gefühlsmelodie"/>
		<OPTIONALDEVOTION name="Gewinnendes Lächeln"/>
		<OPTIONALDEVOTION name="Konversation"/>
		<OPTIONALDEVOTION name="Schauspielern"/>
		<OPTIONALDEVOTION name="Stärkung der Passion"/>
		<OPTIONALDEVOTION name="Unterhalten"/>
		<RANK><!-- 1 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP count="3"/>
			<DEVOTIONBENEFIT spend="tbd by questor"/>
		</RANK>
		<RANK><!-- 2 -->
			<DEVOTIONABILITY/>
		</RANK>
		<RANK><!-- 3 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 4 -->
			<DEVOTIONABILITY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Absichten Einschätzen"/>
		<OPTIONALDEVOTION name="Astendars Muse"/>
		<OPTIONALDEVOTION name="Astendars Stimme"/>
		<OPTIONALDEVOTION name="Bleibender Eindruck"/>
		<OPTIONALDEVOTION name="Diplomatie"/>
		<OPTIONALDEVOTION name="Einsicht der Passion"/>
		<OPTIONALDEVOTION name="Inspiration der Passion"/>
		<OPTIONALDEVOTION name="Verzaubertes Geschenk"/>
		<RANK><!-- 5 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>
		<RANK><!-- 6 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 7 -->
			<DEVOTIONABILITY/>
			<ARMOR name="additional questor armor" mysticarmor="1" weight="0"/>
		</RANK>
		<RANK><!-- 8 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Bardenstimme"/>
		<OPTIONALDEVOTION name="Einfluss Beenden"/>
		<OPTIONALDEVOTION name="Entwaffnendes Lächeln"/>
		<OPTIONALDEVOTION name="Erwachende Liebe"/>
		<OPTIONALDEVOTION name="Fruchtbare Zeiten"/>
		<OPTIONALDEVOTION name="Gedankenkette"/>
		<RANK><!-- 9 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>
		<RANK><!-- 10 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 11 -->
			<DEVOTIONABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
		<RANK><!-- 12 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
			<ARMOR name="additional questor armor" mysticarmor="1" weight="0"/>
		</RANK>
	</TIER>
	<IDEAL>Liebe</IDEAL>
	<IDEAL>Kunst</IDEAL>
	<IDEAL>Musik</IDEAL>
	<!-- Der Questor kann einen Weihepunkt ausgeben für ... .-->
	<DEVOTIONBENEFITEXAMPLE>eine Interaktionsprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um Kunst zu erschaffen, sei es bildende Kunst, eine Vorführung o.Ä.</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, wenn es darum geht, eine Romanze in Gang zu bringen oder zu fördern</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um den romantischen Partner des handelnden Charakters zu schützen</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um mehr über Kunst zu erfahren</DEVOTIONBENEFITEXAMPLE>
</QUESTOR>

=== SushySan/Earthdawn-Character-Editor/config/questors/ED4de/Dis.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<QUESTOR passion="Dis" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawnquestor.xsd">
	<DEVOTION name="Questor" limitation="Dis"/>
	<TIER>
		<OPTIONALDEVOTION name="Detailorientierung"/>
		<OPTIONALDEVOTION name="Einfluss Widerstehen"/>
		<OPTIONALDEVOTION name="Einsicht der Passion"/>
		<OPTIONALDEVOTION name="Eiserner Wille"/>
		<OPTIONALDEVOTION name="Etikette"/>
		<OPTIONALDEVOTION name="Forschen"/>
		<OPTIONALDEVOTION name="Konversation"/>
		<OPTIONALDEVOTION name="Projektmanagement"/>
		<OPTIONALDEVOTION name="Stärkung der Passion"/>
		<OPTIONALDEVOTION name="Verängstigen"/>
		<RANK><!-- 1 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP count="3"/>
			<DEVOTIONBENEFIT spend="tbd by questor"/>
		</RANK>
		<RANK><!-- 2 -->
			<DEVOTIONABILITY/>
		</RANK>
		<RANK><!-- 3 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 4 -->
			<DEVOTIONABILITY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Einfluss Beenden"/>
		<OPTIONALDEVOTION name="Führung"/>
		<OPTIONALDEVOTION name="Inspiration der Passion"/>
		<OPTIONALDEVOTION name="Lebender Tod"/>
		<OPTIONALDEVOTION name="Stählerner Blick"/>
		<OPTIONALDEVOTION name="Starrsinn"/>
		<OPTIONALDEVOTION name="Trostlosigkeit"/>
		<OPTIONALDEVOTION name="Vergifteter Einfluss"/>
		<RANK><!-- 5 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>
		<RANK><!-- 6 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 7 -->
			<DEVOTIONABILITY/>
			<ARMOR name="additional questor armor" mysticarmor="1" weight="0"/>
		</RANK>
		<RANK><!-- 8 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALDEVOTION name="Dis' Herausforderung"/>
		<OPTIONALDEVOTION name="Ketten des Gehorsams"/>
		<OPTIONALDEVOTION name="Untergraben"/>
		<OPTIONALDEVOTION name="Unterwerfen"/>
		<OPTIONALDEVOTION name="Verzaubertes Geschenk"/>
		<OPTIONALDEVOTION name="Zwingen"/>
		<RANK><!-- 9 -->
			<DEVOTIONABILITY/>
			<DEVOTIONDICESTEP/>
			<DEVOTIONBENEFIT spend="tbd by player+gamemaster"/>
		</RANK>
		<RANK><!-- 10 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 11 -->
			<DEVOTIONABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
		<RANK><!-- 12 -->
			<DEVOTIONABILITY/>
			<DEFENSE kind="social"/>
			<ARMOR name="additional questor armor" mysticarmor="1" weight="0"/>
		</RANK>
	</TIER>
	<IDEAL>Verwirrung</IDEAL>
	<IDEAL>unnötige Arbeit</IDEAL>
	<IDEAL>komplexe bürokratische Hierarchien</IDEAL>
	<IDEAL>Sklaverei und Beherrschung</IDEAL>
	<!-- Der Questor kann einen Weihepunkt ausgeben für ... .-->
	<DEVOTIONBENEFITEXAMPLE>eine Interaktionsprobe</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, um ein Ziel zu dominieren.</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Probe, wenn er mit der Bürokratie interagiert</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>die Aktionsprobe eines Untergebenen</DEVOTIONBENEFITEXAMPLE>
	<DEVOTIONBENEFITEXAMPLE>eine Aufrechterhaltene Aktion eines anderen, aber die Vollendung dieser Aktion dauert doppelt so lange wie normal</DEVOTIONBENEFITEXAMPLE>
</QUESTOR>
