=== SushySan/Earthdawn-Character-Editor/config/earthdawncapabilities.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/capability" xmlns="http://earthdawn.com/capability" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:element name="CAPABILITIES">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SKILL" type="edt:CAPABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="TALENT" type="edt:CAPABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DEVOTION" type="edt:DEVOTIONCAPABILITY_type"/>
			</xs:choice>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/capabilities/ED4en/MysticPath.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CAPABILITIES lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/capability" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/capability ../../earthdawncapabilities.xsd">
	<TALENT name="Ancient Bonds" attribute="PER" action="special" strain="1"/>
        <TALENT name="Applied Knowledge" attribute="CHA" action="simple" strain="1"/>
        <TALENT name="Bane Strike" attribute="na" action="free" strain="2"/>
        <TALENT name="Bear Mark" attribute="WIL" action="free" strain="2"/>
        <TALENT name="Body Control" attribute="STR" hasonehandlimitbonus="yes" action="simple" strain="0"/>
        <TALENT name="Brother of Stone" attribute="na" action="na" strain="0"/>
        <TALENT name="Call of Harrow" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Call of Harrow" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Ch’tard Pierce" attribute="DEX" action="simple" strain="2"/>
        <TALENT name="Dance Partner" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Deliberate Assault" attribute="na" action="free" strain="1"/>
        <TALENT name="Dive Attack" attribute="na" action="free" strain="1" skilluse="5"/>
        <TALENT name="Earth Bond" attribute="WIL" action="standard" strain="0"/>
        <TALENT name="Earth Speak" attribute="CHA" action="standard" strain="1"/>
        <TALENT name="Earth Walk" attribute="na" action="sustained" strain="1"/>
        <TALENT name="Edo Dance" attribute="DEX" action="free" strain="1"/>
        <TALENT name="Edo Sweep" attribute="DEX" action="free" strain="2"/>
        <TALENT name="Engaging Dance" attribute="DEX" action="free" strain="1"/>
        <TALENT name="Expansive Expertise" attribute="na" action="na" strain="0"/>
        <TALENT name="Fire Eater" attribute="na" action="na" strain="0"/>
        <TALENT name="Fires of Gahad" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Focused Strike" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Forest Sense" attribute="PER" action="sustained" strain="2"/>
        <TALENT name="Gaze into the Abyss" attribute="na" action="free" strain="1"/>
        <TALENT name="Guardian’s Service" attribute="na" action="simple" strain="1"/>
        <TALENT name="Horror Stalker" attribute="na" action="na" strain="0"/>
        <TALENT name="Journeyman" attribute="na" action="na" strain="0"/>
        <TALENT name="Liberation" attribute="CHA" action="simple" strain="2"/>
        <TALENT name="Liberator" attribute="na" action="na" strain="0"/>
        <TALENT name="Messenger" attribute="na" action="na" strain="0"/>
        <TALENT name="Morphism" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Outcast" attribute="na" action="na" strain="0"/>
        <TALENT name="Patient Resilience" attribute="na" action="free" strain="2"/>
        <TALENT name="Pilot Boat" attribute="PER" action="sustained" skilluse="1"/>
        <TALENT name="Purge Karma" attribute="WIL" action="simple" strain="2"/>
        <TALENT name="Purification" attribute="WIL" action="standard" strain="1"/>
        <TALENT name="Purifier" attribute="na" action="na" strain="0"/>
        <TALENT name="Read River" attribute="PER" action="sustained" strain="0" skilluse="1"/>
        <TALENT name="Rite of Kho’pesh" attribute="na" action="sustained" strain="2"/>
        <TALENT name="Sailing" attribute="DEX" action="sustained" skilluse="1"/>
        <TALENT name="Scholar" attribute="na" action="na" strain="0"/>
        <TALENT name="Sense Captive" attribute="PER" action="standard" strain="1"/>
        <TALENT name="Sense Horrorspawn" attribute="PER" action="standard" strain="1"/>
        <TALENT name="Shatter Will" attribute="WIL" action="free" strain="2"/>
        <TALENT name="Shivoavara Dance" attribute="DEX" action="free" strain="1"/>
        <TALENT name="Shivoavara Escalation" attribute="DEX" action="simple" strain="1"/>
        <TALENT name="Shout of Justice" attribute="CHA" action="simple" strain="1"/>
        <TALENT name="Skora Dance" attribute="DEX" action="free" strain="1"/>
        <TALENT name="Skora Slam" attribute="DEX" action="free" strain="2"/>
        <TALENT name="Spirit Covenant" attribute="CHA" action="standard" strain="2"/>
        <TALENT name="Studied Counter" attribute="PER" action="simple" strain="1" skilluse="5"/>
        <TALENT name="Swimming" attribute="STR" action="standard" skilluse="1" canimprovised="yes"/>
        <TALENT name="Tail Dance" attribute="DEX" action="free" strain="1" skilluse="9"/>
        <TALENT name="Tail Dancer" attribute="na" action="na" strain="0"/>
        <TALENT name="Tail Spike" attribute="STR" bonus="3" action="simple" strain="0"/>
        <TALENT name="Tyranny’s Ruin" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Windmaster" attribute="na" action="na" strain="0"/>
        <TALENT name="Wing Blitz" attribute="na" action="free" strain="1"/>
        <TALENT name="Wisdom of Ages" attribute="WIL" action="sustained" strain="2"/>
        <TALENT name="Wood Speak" attribute="CHA" action="standard" strain="1"/>
        <TALENT name="Wood Walk" attribute="na" action="simple" strain="1"/>
        <TALENT name="Woodsman" attribute="na" action="na" strain="0"/>
</CAPABILITIES>

=== SushySan/Earthdawn-Character-Editor/config/capabilities/ED4de/Companion.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CAPABILITIES lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/capability" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/capability ../../earthdawncapabilities.xsd">
	<TALENT name="Adlerauge" attribute="na" action="free" strain="1"/>
	<TALENT name="Ansporn" attribute="CHA" action="standard"/>
	<TALENT name="Astralangriff" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Astrale Domäne" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Astraltasche" attribute="PER" action="standard" strain="1 (s. Text)"/>
	<TALENT name="Ätherwaffe" attribute="WIL" action="simple" strain="2"/>
	<TALENT name="Aurarüstung" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Bardenstimme" attribute="na" action="free" strain="1"/>
	<TALENT name="Beherrschung der Elemente" attribute="na" action="free" strain="2"/>
	<TALENT name="Beschwörungskreis" attribute="na" action="sustained" strain="1+"/>
	<TALENT name="Blind Schießen" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Blut des Todesmeers" attribute="na" action="free"/>
	<TALENT name="Blutiger Einblick" attribute="PER" action="sustained" strain="1"/>
	<TALENT name="Brennende Kraft" attribute="STR" action="free"/>
	<TALENT name="Chamäleon" attribute="na" action="free" strain="1"/>
	<TALENT name="Dämonen Entgegentreten" attribute="CHA" action="standard" strain="5"/>
	<TALENT name="Dauerfeuer" attribute="PER" action="simple" strain="+1 (s. Text)"/>
	<TALENT name="Donnernde Entschlossenheit" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Durchbohrender Angriff" attribute="na" action="free" strain="1"/>
	<TALENT name="Echolot" attribute="na" action="free" strain="1"/>
	<TALENT name="Eidetisches Gedächtnis" attribute="WIL" action="simple" strain="1"/>
	<TALENT name="Eisiger Schlag" attribute="na" action="free" strain="1"/>
	<TALENT name="Elementarwandeln" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Entwaffnendes Lächeln" attribute="CHA" action="standard" strain="1"/>
	<TALENT name="Fesselnde Visionen" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Fleisch Schmieden" attribute="WIL" action="free" strain="2"/>
	<TALENT name="Fließende Bewegung" attribute="na" action="simple" strain="1+"/>
	<TALENT name="Fluchtplan" attribute="PER" action="sustained" strain="1"/>
	<TALENT name="Gedächtnis Durchdringen" attribute="na" action="free"/>
	<TALENT name="Gedanken Verbergen" attribute="na" action="free"/>
	<TALENT name="Geistessonde" attribute="CHA" action="sustained" strain="3"/>
	<TALENT name="Geistwandeln" attribute="WIL" action="standard" strain="5"/>
	<TALENT name="Gepanzerte Matrix" attribute="na" action="na"/>
	<TALENT name="Gespleißtes Gewebe" attribute="na" action="simple" strain="1+ (s. Text)"/>
	<TALENT name="Gestalt des Bluthundes" attribute="na" action="sustained" strain="1"/>
	<TALENT name="Gift" attribute="TOU" action="free" strain="1"/>
	<TALENT name="Glyphe der Entflechtung" attribute="na" action="free" strain="1"/>
	<TALENT name="Glyphe der Neuabstimmung" attribute="PER" action="simple" strain="3"/>
	<TALENT name="Glyphe der Spiegelung" attribute="PER" action="free" strain="2"/>
	<TALENT name="Glyphe des Schutzes" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Herausforderung der Besten" attribute="CHA" action="standard"/>
	<TALENT name="Heulen" attribute="CHA" action="simple" strain="2"/>
	<TALENT name="Koordinierter Angriff" attribute="CHA" action="standard" strain="1"/>
	<TALENT name="Kritischer Treffer" attribute="na" action="free" skilluse="9"/>
	<TALENT name="Lebendige Waffe" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Lied der Ablenkung" attribute="CHA" action="standard" strain="1"/>
	<TALENT name="Lied der Schlachten" attribute="na" action="free" strain="1"/>
	<TALENT name="Löwenmut" attribute="na" action="na"/>
	<TALENT name="Matrixsicht" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Mehrfacher Schlag" attribute="DEX" action="simple" strain="+1 (s. Text)"/>
	<TALENT name="Mehrfacher Sturmangriff" attribute="DEX" action="simple" strain="+1 (s. Text)"/>
	<TALENT name="Perfekte Konzentration" attribute="WIL" action="simple"/>
	<TALENT name="Pflanzensprache" attribute="PER" action="standard"/>
	<TALENT name="Projektil Beeinflussen" attribute="WIL" action="free" strain="2"/>
	<TALENT name="Rankenrüstung" attribute="na" action="free"/>
	<TALENT name="Schlagfertige Erwiderung" attribute="CHA" action="free" strain="2" skilluse="9"/>
	<TALENT name="Schmerzen Widerstehen" attribute="na" action="na" skilluse="9"/>
	<TALENT name="Schnappschuss" attribute="DEX" action="free" strain="2"/>
	<TALENT name="Schneidende Worte" attribute="CHA" action="simple" strain="2"/>
	<TALENT name="Schockbehandlung" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Seele des Jenseits" attribute="WIL" action="standard"/>
	<TALENT name="Seelenschutz" attribute="WIL" action="standard" strain="1"/>
	<TALENT name="Steinhaut" attribute="na" action="standard"/>
	<TALENT name="Struktur Beeinflussen" attribute="PER" action="simple" strain="2"/>
	<TALENT name="Sturmschild" attribute="na" action="standard" strain="2"/>
	<TALENT name="Summenmatrix" attribute="na" action="na"/>
	<TALENT name="Talentdiebstahl" attribute="WIL" action="standard" strain="2"/>
	<TALENT name="Täuschende Klinge" attribute="na" action="free" strain="1"/>
	<TALENT name="Tiere Führen" attribute="CHA" action="standard"/>
	<TALENT name="Tödlicher Schlag" attribute="TOU" action="free" strain="2"/>
	<TALENT name="Traumdieb" attribute="PER" action="standard" strain="2"/>
	<TALENT name="Üble Wunde" attribute="PER" action="simple" strain="2" skilluse="9"/>
	<TALENT name="Unaufhaltsame Erholung" attribute="TOU" action="free"/>
	<TALENT name="Unmögliches Versteck" attribute="na" action="standard" strain="3"/>
	<TALENT name="Untergraben" attribute="CHA" action="simple" strain="1"/>
	<TALENT name="Unverzagte Tapferkeit" attribute="na" action="na"/>
	<TALENT name="Verteidigungshaltung" attribute="na" action="free" strain="1" skilluse="9"/>
	<TALENT name="Vitaler Schutz" attribute="na" action="free" strain="1"/>
	<TALENT name="Vom Donner Gerührt" attribute="STR" action="free" strain="1"/>
	<TALENT name="Waffenbruch" attribute="na" action="free" skilluse="9"/>
	<TALENT name="Wahrheit Durch Lügen" attribute="CHA" action="standard" strain="2"/>
	<TALENT name="Weltenpuls" attribute="PER" action="sustained" strain="3"/>
	<TALENT name="Wettstreit des Willens" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Wie Eine Streunende Katze" attribute="PER" action="standard"/>
	<TALENT name="Zauberreichweite" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Zauberstruktur" attribute="PER" action="simple" strain="2"/>
	<TALENT name="Zielerfassung" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Zweite Chance" attribute="CHA" action="free" strain="3"/>
	<TALENT name="Zweiter Zauber" attribute="PER" action="simple" strain="2"/>
</CAPABILITIES>

=== SushySan/Earthdawn-Character-Editor/config/capabilities/ED4en/Compendium.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CAPABILITIES lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/capability" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/capability ../../earthdawncapabilities.xsd">
	
        <TALENT name="Alley Cat Approach" attribute="PER" action="standard" strain="0"/>
        <TALENT name="Animal Leadership" attribute="CHA" action="standard" strain="0"/>
        <TALENT name="Armored Matrix" attribute="na" action="na" strain="0"/>
        <TALENT name="Astral Domain" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Astral Pocket" attribute="PER" action="standard" strain="1"/>
        <TALENT name="Aura Armor" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Bardic Voice" attribute="na" action="free" strain="1"/>
        <TALENT name="Beguiling Blade" attribute="na" action="free" strain="1"/>
        <TALENT name="Blind Fire" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Blood Insight" attribute="PER" action="sustained" strain="1"/>
        <TALENT name="Blood of Deathâ€™s Sea" attribute="na" action="free" strain="0"/>
        <TALENT name="Bloodhound Form" attribute="na" action="sustained" strain="1"/>
        <TALENT name="Burning Vigor" attribute="STR" action="free" strain="0"/>
        <TALENT name="Casting Pattern" attribute="PER" action="simple" strain="2"/>
        <TALENT name="Chameleon" attribute="na" action="free" strain="1"/>
        <TALENT name="Champion Challenge" attribute="CHA" action="standard" strain="0"/>
        <TALENT name="Chilling Strike" attribute="na" action="free" strain="1"/>
        <TALENT name="Concentrated Assault" attribute="CHA" action="standard" strain="1"/>
        <TALENT name="Concise Casting" attribute="PER" action="simple" strain="2"/>
        <TALENT name="Confront Horror" attribute="CHA" action="standard" strain="5"/>
        <TALENT name="Contest of Wills" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Critical Hit" attribute="na" action="free" strain="0" skilluse="9"/>
        <TALENT name="Cutting Words" attribute="CHA" action="simple" strain="2"/>
        <TALENT name="Defensive Posture" attribute="na" action="free" strain="1" skilluse="9"/>
        <TALENT name="Disarming Smile" attribute="CHA" action="standard" strain="1"/>
        <TALENT name="Dream Thief" attribute="PER" action="standard" strain="2"/>
        <TALENT name="Eagle Eye" attribute="na" action="free" strain="1"/>
        <TALENT name="Echolocation" attribute="na" action="free" strain="1"/>
        <TALENT name="Effect Pattern" attribute="PER" action="simple" strain="2"/>
        <TALENT name="Eidetic Memory" attribute="WIL" action="simple" strain="1"/>
        <TALENT name="Elemental Mastery" attribute="na" action="free" strain="2"/>
        <TALENT name="Elemental Walk" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Enthralling Visions" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Escape Plan" attribute="PER" action="sustained" strain="1"/>
        <TALENT name="Ethereal Weapon" attribute="WIL" action="simple" strain="2"/>
        <TALENT name="Fluid Movement" attribute="na" action="simple" strain="1"/>
        <TALENT name="Forge Flesh" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Glyph of Attunement" attribute="PER" action="simple" strain="3"/>
        <TALENT name="Glyph of Reversal" attribute="PER" action="free" strain="2"/>
        <TALENT name="Glyph of Shielding" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Glyph of Unweaving" attribute="na" action="free" strain="1"/>
        <TALENT name="Goring Attack" attribute="na" action="free" strain="1"/>
        <TALENT name="Howl" attribute="CHA" action="simple" strain="2"/>
        <TALENT name="Impossible Hide" attribute="na" action="standard" strain="3"/>
        <TALENT name="Influence Missile" attribute="WIL" action="free" strain="2"/>
        <TALENT name="Infuse Memory" attribute="na" action="free" strain="0"/>
        <TALENT name="Lion Spirit" attribute="na" action="na" strain="0"/>
        <TALENT name="Living Weapon" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Matrix Sight" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Memory Probe" attribute="CHA" action="sustained" strain="3"/>
        <TALENT name="Missile Lock" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Multi-Charge" attribute="DEX" action="simple" strain="+"/>
        <TALENT name="Multi-Shot" attribute="PER" action="simple" strain="+"/>
        <TALENT name="Multi-Strike" attribute="DEX" action="simple" strain="1"/>
        <TALENT name="Nethersoul" attribute="WIL" action="standard" strain="0"/>
        <TALENT name="Netherwalk" attribute="WIL" action="standard" strain="5"/>
        <TALENT name="Perfect Focus" attribute="WIL" action="simple" strain="0"/>
        <TALENT name="Plant Talk" attribute="PER" action="standard" strain="0"/>
        <TALENT name="Rally" attribute="CHA" action="standard" strain="0"/>
        <TALENT name="Range Pattern" attribute="PER" action="simple" strain="1"/>
        <TALENT name="Relentless Recovery" attribute="TOU" action="free" strain="0"/>
        <TALENT name="Resist Pain" attribute="na" action="na" strain="0" skilluse="9"/>
        <TALENT name="Safe Thought" attribute="na" action="free" strain="0"/>
        <TALENT name="Second Chance" attribute="CHA" action="free" strain="3"/>
        <TALENT name="Shared Matrix" attribute="na" action="na" strain="0"/>
        <TALENT name="Shock Treatment" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Snapshot" attribute="DEX" action="free" strain="2"/>
        <TALENT name="Snatch Talent" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Song of Battle" attribute="na" action="free" strain="1"/>
        <TALENT name="Song of Deflection" attribute="CHA" action="standard" strain="1"/>
        <TALENT name="Soul Aegis" attribute="WIL" action="standard" strain="1"/>
        <TALENT name="Spirit Strike" attribute="WIL" action="standard" strain="2"/>
        <TALENT name="Spliced Weave" attribute="na" action="simple" strain="1"/>
        <TALENT name="Stone Skin" attribute="na" action="standard" strain="0"/>
        <TALENT name="Storm Shield" attribute="na" action="standard" strain="2"/>
        <TALENT name="Summoning Circle" attribute="na" action="sustained" strain="1"/>
        <TALENT name="Thunderous Resolve" attribute="WIL" action="free" strain="1"/>
        <TALENT name="Thunderstruck" attribute="STR" action="free" strain="1"/>
        <TALENT name="Truth Through Lies" attribute="CHA" action="standard" strain="2"/>
        <TALENT name="Undermine" attribute="CHA" action="simple" strain="1"/>
        <TALENT name="Unflinching Fortitude" attribute="na" action="na" strain="0"/>
        <TALENT name="Venom" attribute="TOU" action="free" strain="1"/>
        <TALENT name="Vicious Wound" attribute="PER" action="simple" strain="2" skilluse="9"/>
        <TALENT name="Vine Armor" attribute="na" action="free" strain="0"/>
        <TALENT name="Vital Strike" attribute="TOU" action="free" strain="2"/>
        <TALENT name="Vital Ward" attribute="na" action="free" strain="1"/>
        <TALENT name="Weapon Breaker" attribute="na" action="free" strain="0" skilluse="9"/>
        <TALENT name="Witty Repartee" attribute="CHA" action="free" strain="2" skilluse="9"/>
        <TALENT name="World Pulse" attribute="PER" action="sustained" strain="3"/>

</CAPABILITIES>
