=== SushySan/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Samurai.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Samurai" lang="en" bookref="CPG p.54" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY circle="1" death="9" unconsciousness="7"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Charge"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Trick Riding"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Kiai"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Missile Weapons"/>
		<DISCIPLINETALENT name="Parry"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Block and Counter"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Mystic Aim"/>
		<OPTIONALTALENT name="Sure Mount"/>
		<OPTIONALTALENT name="Tactics"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Anticipate Blow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Riposte"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Daisho Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Diplomacy"/>
		<OPTIONALTALENT name="Joint Lock"/>
		<OPTIONALTALENT name="Long Shot"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Momentum Attack"/>
		<OPTIONALTALENT name="Second Weapon"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<OPTIONALTALENT name="Wheeling Attack"/>
		<DISCIPLINETALENT name="Shadow Step"/>
		<TALENTABILITY/>
		<ABILITY>Daimyo’s Authority</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="True Shot"/>
		<TALENTABILITY/>
		<KARMA spend="Strength-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Guard Stance"/>
		<TALENTABILITY/>
		<KARMA spend="Damage Tests fighting his lord’s interests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Crushing Blow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
		<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Blind Fire"/>
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Mount Attack"/>
		<OPTIONALTALENT name="Rally"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Takedown"/>
		<DISCIPLINETALENT name="Cobra Strike"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Daimyo’s Command</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Great Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Vitality"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Screaming Arrow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Aura Armor"/>
		<OPTIONALTALENT name="Infuse Weapon"/>
		<OPTIONALTALENT name="Mind Blade"/>
		<OPTIONALTALENT name="Missile Twister"/>
		<OPTIONALTALENT name="Trample"/>
		<OPTIONALTALENT name="Vital Strike"/>
		<DISCIPLINETALENT name="Ethereal Weapon"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Daimyo’s Entitlement</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Multi-Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Multi-Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>maintain his weapons/ armor, care for his mount; knowledge: military tactics/ strategy, concerning samurai life, code of bushido, Jih’Pen nobles and their culture; Skill: Tactics, Etiquette, Conversation if situation concerns Jih’Pen culture;(CPG p.56)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Merchant.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Merchant" lang="en" bookref="CPG p.40" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Bribery"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Etiquette"/>
		<DISCIPLINETALENT name="Evaluate"/>
		<DISCIPLINETALENT name="First Impression"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Trading"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Dead Fall"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Slough Blame"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<DISCIPLINETALENT name="Empathic Sense"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Conceal Object"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Profit Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Abate Curse"/>
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Diplomacy"/>
		<OPTIONALTALENT name="Direction Sense"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Fast Hand"/>
		<OPTIONALTALENT name="Lip Reading"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<DISCIPLINETALENT name="Assess Community"/>
		<TALENTABILITY/>
		<ABILITY>Procure Item</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Safe Path"/>
		<TALENTABILITY/>
		<KARMA spend="Action Tests to defend his property against theft or robbery"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="True Sight"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
		<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Astral Pocket"/>
		<OPTIONALTALENT name="Bardic Voice"/>
		<OPTIONALTALENT name="Defense"/>
		<OPTIONALTALENT name="Detect Falsehood"/>
		<OPTIONALTALENT name="Infuse Weapon"/>
		<OPTIONALTALENT name="Power Mask"/>
		<OPTIONALTALENT name="Safe Thought"/>
		<OPTIONALTALENT name="Show Armor Flaw"/>
		<DISCIPLINETALENT name="Gold Sense"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>A Contract is a Contract</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Disguise Chest"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Sense Magic Item"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Conceal Caravan"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Gain Surprise"/>
		<OPTIONALTALENT name="Infuse Armor"/>
		<OPTIONALTALENT name="Moving Earth"/>
		<OPTIONALTALENT name="Multi-Tongue"/>
		<OPTIONALTALENT name="Reshape Object"/>
		<OPTIONALTALENT name="Soften Blade"/>
		<DISCIPLINETALENT name="Chameleon"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMASTEP/>
		<ABILITY>Evaluate Customer</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Company of One"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: everything related to trade (important trade routes, customs regarding trade, trade laws, clauses in contracts); in place Interaction (Insight) Tests, apply them documents to spot dangerous clauses in fine print; Skill: Navigation, Mapmaking;(CPG p.42) </HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Swordmaster-Gallant.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Swordmaster-Gallant" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="7" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="First Impression"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Parry"/>
		<DISCIPLINETALENT name="Taunt"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<DISCIPLINETALENT name="Winning Smile"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Riposte"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Weapon Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Disarm"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Second Weapon"/>
		<TALENTABILITY/>
		<ABILITY>Flourish</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Lasting Impression"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<KARMA spend="mele weapon Damage Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Second Attack"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
		<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Mind Blade"/>
		<OPTIONALTALENT name="Pin"/>
		<OPTIONALTALENT name="Shield Beater"/>
		<OPTIONALTALENT name="Shield Charge"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<OPTIONALTALENT name="Whirlwind"/>
		<DISCIPLINETALENT name="Impressive Strike"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Weapon Bond</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Champion Challenge"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Spot Armor Flaw"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Defense"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Infuse Blade"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Mind Armor"/>
		<OPTIONALTALENT name="Missile Twister"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<OPTIONALTALENT name="Second Chance"/>
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMASTEP/>
		<ABILITY>Keen Blade</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Multi-Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Ethereal Weapon"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<DEFENSE kind="mystic"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>care their weapons; knowledge: history legendary weapons, types melee weapons; identify Swordmaster’s fighting techniques, including which prominent Swordmasters shaped individual’s style;(PG p.51)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4en/Sailor.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Sailor" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Defense"/>
		<OPTIONALTALENT name="Distract"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Taunt"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<FREETALENT name="Sailing"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Climbing"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="Sea Weaving"/>
		<DISCIPLINETALENT name="Swimming"/>
		<TALENTABILITY/>
		<KARMA spend="once per round on any action taken while on board an airship"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Awareness"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Empathic Sense"/>
		<TALENTABILITY/>
		<KARMA spend="on Initiative tests"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Wound Balance"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Battle Bellow"/>
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Engaging Banter"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Second Weapon"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<DISCIPLINETALENT name="Heartening Laugh"/>
		<TALENTABILITY/>
		<KARMA spend="on Interaction Tests"/>
		<ABILITY>Collaborate</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Air Dance"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Inspire Others"/>
		<TALENTABILITY/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Lion Heart"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>The Boatman sits alone in silent meditation preferably near a river or other body of water for several minutes, picturing in their mindâ€™s eye their riverboat cruising through the current at the start of a long journey. The adept envisions a journey they hope to make one day, imagining scenes of this journey, including the risks and perils, and how their training and skills might help make the journey a safe one. The ritual is complete when, half an hour later, the imagined journey ends safely.</KARMARITUAL>
	<HALFMAGIC>The Sailor uses Half-Magic for knowledge of ship designs, recognition of different kinds of ships, common sea trade routes, and ship crew compliments. It also covers the maintenance, repair, and construction of ships.</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Messenger.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Messenger" lang="en" bookref="NG p.163" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Book Memory"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Read/Write Language"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Direction Sense"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Navigation"/>
		<DISCIPLINETALENT name="Speak Language"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Book Recall"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<DISCIPLINETALENT name="Conceal Object"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Sprint"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Message Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Detect Trap"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Gliding Stride"/>
		<OPTIONALTALENT name="Mimic Voice"/>
		<OPTIONALTALENT name="Trick Riding"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Temper Self"/>
		<TALENTABILITY/>
		<ABILITY>Encrypt</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Steel Thought"/>
		<TALENTABILITY/>
		<KARMA spend="Action Test to defend an outside influence that might prevent him from delivering a message"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Safe Path"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Fast Hand"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Lifesight"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Missile Twister"/>
		<OPTIONALTALENT name="Plant Shelter"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Lion Spirit"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Endurance</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Safe Thought"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="True Sight"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Chameleon"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Defense"/>
		<OPTIONALTALENT name="Detect Falsehood"/>
		<OPTIONALTALENT name="Ethereal Weapon"/>
		<OPTIONALTALENT name="Multi-Tongue"/>
		<OPTIONALTALENT name="Stone Skin"/>
		<OPTIONALTALENT name="Truth Skit"/>
		<DISCIPLINETALENT name="Elemental Walk"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMASTEP/>
		<ABILITY>One with the Message</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Echo Location"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: travel routes, customs of delivery trade, messages types, how to convey, hide, find, encrypt, decrypt; Toughness-based Tests in place Fatigue Tests; Skill: Mapmaking, Wilderness Survival;(NG p.163)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Pugilist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Pugilist" lang="en" bookref="CPG p.50" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="9" unconsciousness="7"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Close In"/>
		<OPTIONALTALENT name="Impress"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Block and Counter"/>
		<DISCIPLINETALENT name="Jab"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Performance"/>
		<DISCIPLINETALENT name="Unarmed Combat"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Distract"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Lasting Impression"/>
		<OPTIONALTALENT name="Rapid Strike"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Winning Smile"/>
		<DISCIPLINETALENT name="Cross"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Hook"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Fist Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Engaging Dance"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Momentum Attack"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Steely Stare"/>
		<OPTIONALTALENT name="Taunt"/>
		<DISCIPLINETALENT name="Combo"/>
		<TALENTABILITY/>
		<ABILITY>Find Opening</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Uppercut"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Lightning Combo"/>
		<TALENTABILITY/>
		<KARMA spend="unarmed Damage Tests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Temper Self"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
		<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Bedazzle"/>
		<OPTIONALTALENT name="Cobra Strike"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Incite Mob"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Pin"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Vitality"/>
		<DISCIPLINETALENT name="Champion Challenge"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Break</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Absorb Blow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMA spend="Strength-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Impressive Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Knockout"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Bardic Voice"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Phantom Strike"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Second Chance"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Superior Footwork</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Multi-Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Aura Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: physical fitness, tests to find/ set up bout in town/ city, customs regarding conduction of bout; Perception-based Tests: Pugilists they observe fighting determine his style and teacher;(CPG p.53)</HALFMAGIC>
</DISCIPLINE>
