=== SushySan/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/WindScout.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Wind Scout" lang="en" bookref="NG p.209" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Missile Weapons"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Evidence Analysis"/>
		<DISCIPLINETALENT name="Tracking"/>
		<DISCIPLINETALENT name="Wilderness Survival"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Detect Trap"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Animal Bond"/>
		<OPTIONALTALENT name="Lifesight"/>
		<DISCIPLINETALENT name="Search"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Scent Identifier"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Scent Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Mystic Aim"/>
		<OPTIONALTALENT name="Direction Arrow"/>
		<OPTIONALTALENT name="Disarm Trap"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Wind Dance"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Bird Song"/>
		<TALENTABILITY/>
		<ABILITY>Step Outside</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Endure Cold"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Sense Poison"/>
		<TALENTABILITY/>
		<KARMA spend="gather information by Smell Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Safe Path"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Air Dance"/>
		<OPTIONALTALENT name="Animal Possession"/>
		<OPTIONALTALENT name="Bestial Resilience"/>
		<OPTIONALTALENT name="Bestial Toughness"/>
		<OPTIONALTALENT name="Dive Attack"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Thought Link"/>
		<DISCIPLINETALENT name="True Sight"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Reconnaissance</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Chameleon"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Plant Shelter"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Defense"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Elemental Walk"/>
		<OPTIONALTALENT name="Ethereal Weapon"/>
		<OPTIONALTALENT name="Missile Twister"/>
		<OPTIONALTALENT name="Multi-Tongue"/>
		<OPTIONALTALENT name="Netherwalk"/>
		<OPTIONALTALENT name="Show Armor Flaw"/>
		<DISCIPLINETALENT name="Echo Location"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMASTEP/>
		<ABILITY>Wing Mastery</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Develop Animal Sense"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>recognize scents, tracks, trails left by animals, plants, Namegivers in wilderness environments; Skill: Search, Detect Trap, Navigation; (NG p.211)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/GuardianOfCathay.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Guardian of Cathay" lang="en" bookref="CPG p.35" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="9" unconsciousness="7"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Tracking"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Fireblood"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Maneuver"/>
		<DISCIPLINETALENT name="Parry"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Lasting Impression"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Shield Charge"/>
		<OPTIONALTALENT name="Tactics"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<DISCIPLINETALENT name="Clay Skin"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Air Dance"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Duty Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Diplomacy"/>
		<OPTIONALTALENT name="Direction Sense"/>
		<OPTIONALTALENT name="Elemental Tongues"/>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Sprint"/>
		<DISCIPLINETALENT name="Steel Thought"/>
		<TALENTABILITY/>
		<ABILITY>Emperorâ€™s Emissary</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Cobra Strike"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Momentum Attack"/>
		<TALENTABILITY/>
		<KARMA spend="against enemy of his kingdom"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Flowing Blow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>	
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Detect Falsehood"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Pin"/>
		<OPTIONALTALENT name="Rally"/>
		<OPTIONALTALENT name="Vitality"/>
		<DISCIPLINETALENT name="Liquid Prison"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Strength of the Realm</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Metal Ward"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMA spend="Strength-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Fiery Blade"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Airs of Nobility"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Blood Guilt Weapon"/>
		<OPTIONALTALENT name="Elemental Walk"/>
		<OPTIONALTALENT name="Infuse Blade"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<OPTIONALTALENT name="Shield of the Innocent"/>
		<OPTIONALTALENT name="Storm Shield"/>
		<DISCIPLINETALENT name="Earth Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Spirit Guardian</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Multi-Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: military strategy/ tactics, his kingdom and its laws; taking care arms/ armor; Skill: Tactics; (CPG p.36)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4en/Beastmaster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Beastmaster" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="7" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Defense"/>
		<OPTIONALTALENT name="Animal Bond"/>
		<OPTIONALTALENT name="Animal Training"/>
		<OPTIONALTALENT name="Borrow Sense"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Enhance Animal Companion"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<OPTIONALTALENT name="Tracking"/>
		<DISCIPLINETALENT name="Avoid Blow"/>
		<DISCIPLINETALENT name="Claw Shape"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="Beast Weaving"/>
		<DISCIPLINETALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Wilderness Survival"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Awareness"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Dominate Beast"/>
		<TALENTABILITY/>
		<KARMA spend="on Recovery Tests"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Great Leap"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Animal Companion Durability"/>
		<OPTIONALTALENT name="Animal Possession"/>
		<OPTIONALTALENT name="Battle Bellow"/>
		<OPTIONALTALENT name="Call Animal Companion"/>
		<OPTIONALTALENT name="Cobra Strike"/>
		<OPTIONALTALENT name="Iron Constitution"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Blood Share"/>
		<TALENTABILITY/>
		<KARMA spend="on a Damage test made with unarmed combat"/>
		<ABILITY>Cat's Grace</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Animal Talk"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Down Strike"/>
		<TALENTABILITY/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Claw Frenzy"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>Dealing with or caring for animals, including animal husbandry and first aid. Recognizing different animals, animal tracks, and abnormal behavior among animals/creatures</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4de/Waffenschmied.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Waffenschmied" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Aufmerksamkeit"/>
		<OPTIONALTALENT name="Erster Eindruck"/>
		<OPTIONALTALENT name="Fallen Entschärfen"/>
		<OPTIONALTALENT name="Feilschen"/>
		<OPTIONALTALENT name="Feuerblut"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Gefahrensinn"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Lesen/Schreiben"/>
		<OPTIONALTALENT name="Schildschlag"/>
		<FREETALENT name="Handwerk"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Faden Schmieden"/>
		<DISCIPLINETALENT name="Artefaktgeschichte"/>
		<DISCIPLINETALENT name="Eiserner Wille"/>
		<DISCIPLINETALENT name="Nahkampfwaffen"/>
		<DISCIPLINETALENT name="Waffe Schmieden"/>
		<TALENTABILITY/>
		<KARMA spend="jede Probe um einen Gegenstand herzustellen oder zu reparieren"/>
		<ABILITY>Handwerker</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Konversation"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Fluch Unterdrücken"/>
		<TALENTABILITY/>
		<KARMA spend="Erholungsproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Standhaftigkeit"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Diplomatie"/>
		<OPTIONALTALENT name="Eiserne Konstitution"/>
		<OPTIONALTALENT name="Erdhaut"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Führung"/>
		<OPTIONALTALENT name="Heilendes Feuer"/>
		<OPTIONALTALENT name="Herzliches Lachen"/>
		<OPTIONALTALENT name="Kampfgebrüll"/>
		<OPTIONALTALENT name="Projektilwaffen"/>
		<OPTIONALTALENT name="Starrsinn"/>
		<DISCIPLINETALENT name="Rüstung Schmieden"/>
		<TALENTABILITY/>
		<KARMA spend="Schadensproben mit Waffen die selbst hergestellt sind"/>
		<ABILITY>Reisende Schmiede</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Ätherhaut"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Schwachstelle Erkennen"/>
		<TALENTABILITY/>
		<RECOVERYTESTSTEP/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Löwenherz"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Pflege von Waffen und Rüstungen; Erkennen von Waffen und Rüstungen und ihre Hersteller</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED3en/Beastlord.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Beastlord" lang="en" bookref="CPG p.26" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Tracking"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Creature Analysis"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Manifest Beast"/>
		<DISCIPLINETALENT name="Past Tongues"/>
		<DISCIPLINETALENT name="Sense Animals"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Animal Training"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Frighten Animals"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<DISCIPLINETALENT name="Calm Beast"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Empathic Sense"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Way Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Blood Share"/>
		<OPTIONALTALENT name="Hypnotize"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Taunt"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Beast Summons"/>
		<TALENTABILITY/>
		<ABILITY>Sense Motive</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Animal Slumber"/>
		<TALENTABILITY/>
		<KARMA spend="Action Tests made by one of his manifested or tasked animals"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Inherited Powers"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Animal Leadership"/>
		<OPTIONALTALENT name="Bestial Toughness"/>
		<OPTIONALTALENT name="Endure Cold"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Incite Mob"/>
		<OPTIONALTALENT name="Incite Stampede"/>
		<OPTIONALTALENT name="Tame Mount"/>
		<OPTIONALTALENT name="Thought Link"/>
		<DISCIPLINETALENT name="Task Kin"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>True Self</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Detect Falsehood"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Howl"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="physical"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Develop Animal Sense"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Aura Armor"/>
		<OPTIONALTALENT name="Bestial Resilience"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Scent Identifier"/>
		<OPTIONALTALENT name="Second Chance"/>
		<OPTIONALTALENT name="True Sight"/>
		<DISCIPLINETALENT name="Bardic Voice"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<KARMASTEP/>
		<ABILITY>True Strength</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Chameleon"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Spirit Blend"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: animalâ€™s behaviour, character, likely reactions in situations, (not physical traits); Skill: Wilderness Survival; intuition strengthened by half-magic; for Interaction (Insight) Tests; recognize Animal Selves important to other Beastlords;(CPG p.28)</HALFMAGIC>
</DISCIPLINE>

=== SushySan/Earthdawn-Character-Editor/config/disciplines/ED4de/Schütze.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Schütze" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Aufmerksamkeit"/>
		<OPTIONALTALENT name="Beeindrucken"/>
		<OPTIONALTALENT name="Erster Eindruck"/>
		<OPTIONALTALENT name="Heimlicher Schritt"/>
		<OPTIONALTALENT name="Klettern"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Spurenlesen"/>
		<OPTIONALTALENT name="Tieranalyse"/>
		<OPTIONALTALENT name="Wildnisüberleben"/>
		<OPTIONALTALENT name="Wurfwaffen"/>
		<FREETALENT name="Projektil Rufen"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Pfeil Weben"/>
		<DISCIPLINETALENT name="Blattschuss"/>
		<DISCIPLINETALENT name="Hieb Ausweichen"/>
		<DISCIPLINETALENT name="Magische Markierung"/>
		<DISCIPLINETALENT name="Projektilwaffen"/>
		<TALENTABILITY/>
		<KARMA spend="Wahrnehmungsproben auf Sicht basierend"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Mystische Verfolgung"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Kampfsinn"/>
		<TALENTABILITY/>
		<KARMA spend="Initiativeproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Weitschuss"/>
		<TALENTABILITY/>
		<DEFENSE kind="mystic"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Ablenken"/>
		<OPTIONALTALENT name="Bannmarkierung"/>
		<OPTIONALTALENT name="Beweisanalyse"/>
		<OPTIONALTALENT name="Eiserner Wille"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Gefahrensinn"/>
		<OPTIONALTALENT name="Konversation"/>
		<OPTIONALTALENT name="Starrsinn"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<DISCIPLINETALENT name="Schwachstelle Erkennen"/>
		<TALENTABILITY/>
		<KARMA spend="Schadensproben mit Fernkampfwaffen"/>
		<ABILITY>Projektil Erschaffen</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Gezielter Querschläger"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Brandpfeil"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Zweiter Schuss"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Pflege von Fernkampfwaffen; Erkennen aller Arten von  Fernkampfwaffen, Munition oder Hersteller</HALFMAGIC>
</DISCIPLINE>
