=== SushySan/Earthdawn-Character-Editor/config/earthdawnpath.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/path" xmlns="http://earthdawn.com/path" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="PATHRANK_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PATHTIER_type">
		<xs:annotation><xs:documentation>The path ranks are grouped by tiers</xs:documentation></xs:annotation>
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="15" name="RANK" type="PATHRANK_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="edt:tierkind_type" default="auto">
			<xs:annotation><xs:documentation>By default the tier kind is determinate automatically, starting with novice. At any point, it is possible to skip one tier kind and have the following tier kinds automatically be determinate again. The tier kind order must never be mixed. You must never use a lower tier kind after a higher tier kind. The order is: novice, journeyman, warden, master. The tier kind “auto” is always possible.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="PATH">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="NEEDEDKNACK" type="xs:string"><xs:annotation><xs:documentation>This knack must be learned to access this path.</xs:documentation></xs:annotation></xs:element>
				<xs:element minOccurs="1" maxOccurs="1" name="TALENT" type="edt:TALENTABILITY_type"/>
				<xs:element minOccurs="1" maxOccurs="4" name="TIER" type="PATHTIER_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED4"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Horror Stalker.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Horror Stalker" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Horror Stalker</NEEDEDKNACK>
	<TALENT name="Horror Stalker" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Bear Mark"/>
		<OPTIONALTALENT name="Call of Harrow"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Mystic Pursuit"/>
		<OPTIONALTALENT name="Research"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<OPTIONALTALENT name="Suppress Curse"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Bane Strike"/>
		<OPTIONALTALENT name="Gaze into the Abyss"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Purge Karma"/>
		<OPTIONALTALENT name="Sense Horrorspawn"/>
		<OPTIONALTALENT name="True Sight"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<ARMOR name="additional path bonus" weight="0" used="yes" location="self" mysticarmor="1"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Netherwalk"/>
		<OPTIONALTALENT name="Relentless Recovery"/>
		<OPTIONALTALENT name="Unflinching Fortitude"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Horror Stalkersâ€™ Karma Rituals incorporate their sworn hunt in some way, whether the search for information about them, memories of those lost to them, or their active quest to destroy them.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Horror Stalkers and know the history of Horror Stalkers. Additionally, the adept can use Perception-based Half-Magic in place of any Horror Lore tests.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Scholar.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Scholar" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Scholar </NEEDEDKNACK>
	<TALENT name="Scholar" tier="journeyman"/><!-- learned talent with knack on Rank1. The max rank is 5. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Arcane Mutterings"/>
		<OPTIONALTALENT name="Expansive Expertise"/>
		<OPTIONALTALENT name="Book Memory"/>
		<OPTIONALTALENT name="Conversation"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Read and Write Language"/>
		<OPTIONALTALENT name="Research"/>
		<OPTIONALTALENT name="Speak Language"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Applied Knowledge"/>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
	</TIER>
	<KARMARITUAL>The Scholar influences on the adeptâ€™s Karma Ritual are subtle and just as often internal as they are external.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Scholars and know the history of Scholars. Additionally, the adept can use Perceptionbased Half-Magic for information regarding libraries and other academic institutions, and Charisma-based Half-Magic when interacting with the bureaucracy of a library and other academic institutions.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/TailDancerShivoavara.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Tail Dancer (Shiovoavara School)" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Tail Dancer</NEEDEDKNACK>
	<TALENT name="Tail Dancer" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Acrobatic Defense"/>
		<OPTIONALTALENT name="Dance Partner"/>
		<OPTIONALTALENT name="Impressive Display"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Tail Dance"/>
		<OPTIONALTALENT name="Tail Spike"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<OPTIONALTALENT name="Great Leap"/>
                <RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK> 
	</TIER>
        <TIER name="warden">
		<OPTIONALTALENT name="Engaging Dance"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Cobra Strike"/>
		<OPTIONALTALENT name="Shivoavara Dance"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
                </RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
                        <DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<INITIATIVE/>
		</RANK>
	</TIER>
	<TIER name="master">
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Fluid Movement"/>
		<OPTIONALTALENT name="Shivoavara Escalation"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<INITIATIVE/>
		</RANK>
	</TIER>
	<KARMARITUAL>Tail Dancersâ€™ Karma Rituals incorporate dancing and a partner. Combat involving their tail is common, though not universal.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Tail Dancers and know the history of Tail Dancers. Additionally, the adept can use Dexterity-based Half-Magic in place of Dancing tests and Perception-based Half-Magic in place of any Dancing-related knowledge tests.</HALFMAGIC>	
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/BrotherOfStone.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Brother of Stone" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Brother of Stone</NEEDEDKNACK>
	<TALENT name="Brother of Stone" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10 -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Deliberate Assault"/>
		<OPTIONALTALENT name="Earth Bond"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="True Sight"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Earth Skin"/>
		<OPTIONALTALENT name="Earth Speak"/>
		<OPTIONALTALENT name="Earth Walk"/>
		<OPTIONALTALENT name="Iron Constitution"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Temper Self"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Relentless Recovery"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Unflinching Fortitude"/>
		<OPTIONALTALENT name="Wisdom of Ages"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Brothers of Stone conduct their Karma Rituals while in contact with earth or stone and connect with their brotherhood while doing so.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Brothers of Stone and know the history of Brothers of Stone. Additionally, the adept can make a Perception-based Half-Magic test to detect the presence of earth elemental spirits within 30 yards.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Windmaster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Windmaster" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Windmaster</NEEDEDKNACK>
	<TALENT name="Windmaster" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Distract"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<OPTIONALTALENT name="Tactics"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Air Dance"/>
		<OPTIONALTALENT name="Dive Attack"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<OPTIONALTALENT name="Temper Self"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Relentless Recovery"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Defensive Posture"/>
		<OPTIONALTALENT name="Unflinching Fortitude"/>
		<OPTIONALTALENT name="Wing Blitz"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<INITIATIVE/>
		</RANK>
	</TIER>
	<KARMARITUAL>Windmasters Karma Rituals incorporate often dizzying displays of flight and speed; the Karma Rituals magic enables the adept to fly without test or cost for the duration. The air attack is accompanied by a gust of wind focused to a knife-like blade that strikes a distant target.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Windmasters and know the history of Windmasters. Additionally, the adept  can use Half-Magic for knowledge of guerilla and ambush warfare, history of windling battles and tactics, and traditional windling equipment and fightingstyles.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Woodsman.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Woodsman" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Woodsman</NEEDEDKNACK>
	<TALENT name="Woodsman" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Guardian’s Service"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<OPTIONALTALENT name="Tracking"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<OPTIONALTALENT name="Wood Skin"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK> 
	</TIER>
        <TIER name="warden">
		<OPTIONALTALENT name="Mystic Pursuit"/>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<OPTIONALTALENT name="Lifesight"/>
		<OPTIONALTALENT name="Safe Path"/>
		<OPTIONALTALENT name="Wood Speak"/>
		<OPTIONALTALENT name="Wood Walk"/>
                <RANK><!-- 5 -->
			<TALENTABILITY/>
                </RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
                        <DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<INITIATIVE/>
		</RANK>
	</TIER>
	<TIER name="master">
		<OPTIONALTALENT name="Chameleon"/>
		<OPTIONALTALENT name="Forest Sense"/>
		<OPTIONALTALENT name="Plant Talk"/>
		<OPTIONALTALENT name="Vine Armor"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Woodsmen’s Karma Rituals incorporate the forest, protection, or elf culture in some way.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Woodsmen and know the history of Woodsmen. Additionally, the adept can make a Perception-based Half-Magic test to detect the presence of wood elemental spirits within 30 yards.</HALFMAGIC>	
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Messenger.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Messenger" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Messenger</NEEDEDKNACK>
	<TALENT name="Messenger" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Book Memory"/>
		<OPTIONALTALENT name="Conversation"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Read and Write Language"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Orbiting Spy"/>
		<OPTIONALTALENT name="Power Mask"/>
		<OPTIONALTALENT name="Safe Path"/>
		<OPTIONALTALENT name="Spirit Mount"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Astral Pocket"/>
		<OPTIONALTALENT name="Netherwalk"/>
		<OPTIONALTALENT name="Safe Thought"/>
		<OPTIONALTALENT name="Thought Link"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<INITIATIVE/>
		</RANK>
	</TIER>
	<KARMARITUAL>Messenger Karma Rituals are subtly changed, often only noticeable to those closest to the Messenger and other Messengers. Travel is the typical change, with anything else being entirely in how the adept perceives their Karma Ritual.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Messengers and know the history of Messengers. Additionally, the adept can use Perceptionbased Half-Magic for information regarding trade routes or travel perils through an area, and Charisma-based Half-Magic to find transportation.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Liberator.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Liberator" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Liberator</NEEDEDKNACK>
	<TALENT name="Liberator" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 10. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Empathic Sense"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Lock Picking"/>
		<OPTIONALTALENT name="Picking Pockets"/>
		<OPTIONALTALENT name="Sense Captive"/>
		<OPTIONALTALENT name="Stealthy Stride"/>
		<OPTIONALTALENT name="Tyranny’s Ruin"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Inspire Others"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Power Masek"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Shout of Justice"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 6 -->
			<TALENTABILITY/>
			<DEFENSE kind="physical"/>
		</RANK>
		<RANK><!-- 7 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 8 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Escape Plan"/>
		<OPTIONALTALENT name="Liberation"/>
		<OPTIONALTALENT name="Safe Thought"/>
		<OPTIONALTALENT name="Thought Link"/>
		<RANK><!-- 9 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 10 -->
			<TALENTABILITY/>
			<RECOVERYTESTPERDAY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Liberators’ Karma Rituals incorporate an expression of freedom, whether their own or giving it to another.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Liberators and know the history of Liberators. Additionally, the adept can use Perceptionbased Half-Magic for information regarding famous tyrants, oppressive regimes, slavers and slavery, common tactics and ploys of them, and resistance fighters.</HALFMAGIC>
</PATH>
