=== SushySan/Earthdawn-Character-Editor/config/earthdawnknacks.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/knack" xmlns="http://earthdawn.com/knack" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="KNACKRACE_type">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKBASECAPABILITY_type">
				<xs:attribute name="type" type="edt:capabilitytype_type" use="required"/>
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="limitation" type="xs:string" default=""/>
				<xs:attribute name="minrank" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="KNACKDISCIPLINE_type">
				<xs:attribute name="name" type="xs:string" default="*"/>
				<xs:attribute name="circle" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKATTRIBUTE_type">
				<xs:attribute name="name" type="edt:ATTRIBUTE_name_type" use="required"/>
				<xs:attribute name="min" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="max" type="edt:unsigned_int" default="0"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKCAPABILITY_type">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="limitation" type="xs:string" default=""/>
				<xs:attribute name="minrank" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="maxrank" type="edt:unsigned_int" default="0"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
				<xs:attribute name="pool" type="xs:string" default=""><xs:annotation><xs:documentation>Different KNACKCAPABILITY can be grouped by 'pool' and prerequisite is fulfilled, if one of the pool matches. KNACKCAPABILITYs with undefined/empty a pool will not be grouped.</xs:documentation></xs:annotation></xs:attribute>
        </xs:complexType>
	<xs:complexType name="KNACKOTHERKNACK_type">
				<xs:attribute name="name" type="xs:string" default="*"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
        <xs:complexType name="KNACKSPELL_type">
				<xs:attribute name="name" type="xs:string" default="*"/>
                                <xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
        <xs:complexType name="KNACKOTHER_type">
				<xs:attribute name="text" type="xs:string" default="*"/><!-- Other requirment as text which can't be checked but is needed to learn a knack and should be an info for player when choosing the knack. -->
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKDEFINITION_type">
		<xs:complexContent>
			<xs:extension base="edt:KNACKBASE_type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="1" name="BASE" type="KNACKBASECAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="KNACK" type="KNACKOTHERKNACK_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="DISCIPLINE" type="KNACKDISCIPLINE_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="TALENT" type="KNACKCAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="SKILL" type="KNACKCAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="RACE" type="KNACKRACE_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="ATTRIBUTE" type="KNACKATTRIBUTE_type"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="SPELL" type="KNACKSPELL_type"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="OTHER" type="KNACKOTHER_type"/>
				</xs:sequence>
				<xs:attribute name="skilluse" type="edt:unsigned_int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="KNACKS">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KNACK" type="KNACKDEFINITION_type"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/knacks/ED3en/Namegiver.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<KNACKS lang="en" xmlns="http://earthdawn.com/knack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/knack ../../earthdawnknacks.xsd">
	<KNACK name="Backlash"            strain="2"  bookref="NG p.224"><BASE type="talent" minrank="6"  name="Tail Dance"/>                                </KNACK>
	<KNACK name="Beauty of Bloodshed" strain="4"  bookref="NG p.224"><BASE type="talent" minrank="7"  name="Thread Weaving" limitation="Art Weaving"/>   </KNACK>
	<KNACK name="Bluffing Dive"       strain="2"  bookref="NG p.224"><BASE type="talent" minrank="9"  name="Dive Attack"/>                               </KNACK>
	<KNACK name="Body Armor"          strain="1"  bookref="NG p.224"><BASE type="talent" minrank="9"  name="Body Control"/>                              </KNACK>
	<KNACK name="Brandmark Servant"   strain="2"  bookref="NG p.224"><BASE type="talent" minrank="7"  name="Detect Influence"/>                          </KNACK>
	<KNACK name="Break Lock"          strain="2"  bookref="NG p.225"><BASE type="talent" minrank="6"  name="Lock Picking"/>                              </KNACK>
	<KNACK name="Broadside"           strain="4"  bookref="NG p.225"><BASE type="talent" minrank="8"  name="Pilot Boat"/>                                </KNACK>
	<KNACK name="Clay Blend"          strain="2+" bookref="NG p.225"><BASE type="talent" minrank="8"  name="Clay Skin"/>                                 </KNACK>
	<KNACK name="Collective Beating"  strain="1+" bookref="NG p.225"><BASE type="talent" minrank="9"  name="Hoard Blows"/>                               </KNACK>
	<KNACK name="Cover"               strain="1"  bookref="NG p.225"><BASE type="talent" minrank="6"  name="Avoid Blow"/>                                </KNACK>
	<KNACK name="Dive"                strain="2"  bookref="NG p.225"><BASE type="talent" minrank="8"  name="Swimming"/>                                  </KNACK>
	<KNACK name="Dragging Parry"      strain="2"  bookref="NG p.225"><BASE type="talent" minrank="8"  name="Cast Net"/>                                  </KNACK>
	<KNACK name="Endure Heat"         strain="0"  bookref="NG p.226"><BASE type="talent" minrank="5"  name="Endure Cold"/>                               </KNACK>
	<KNACK name="Fake Thought"        strain="2"  bookref="NG p.226"><BASE type="talent" minrank="9"  name="Safe Thought"/>                              </KNACK>
	<KNACK name="Fast Grab"           strain="2"  bookref="NG p.226"><BASE type="talent" minrank="9"  name="Disarm"/>                                    </KNACK>
	<KNACK name="Fast Talk"           strain="2"  bookref="NG p.226"><BASE type="talent" minrank="6"  name="Conversation"/>                              </KNACK>
	<KNACK name="Hiking"              strain="3"  bookref="NG p.226"><BASE type="talent" minrank="9"  name="Woodwalk"/>                                  </KNACK>
	<KNACK name="History Skit"        strain="4"  bookref="NG p.226"><BASE type="talent" minrank="11" name="Truth Skit"/>                                </KNACK>
	<KNACK name="Hoard Spells"        strain="1"  bookref="NG p.226"><BASE type="talent" minrank="9"  name="Hoard Blows"/>                               </KNACK>
	<KNACK name="Hoarded Haunting"    strain="2+" bookref="NG p.226"><BASE type="talent" minrank="8"  name="Hoard Blows"/>                               </KNACK>
	<KNACK name="Incite Monologue"    strain="3"  bookref="NG p.226"><BASE type="talent" minrank="7"  name="Engaging Banter"/>                           </KNACK>
	<KNACK name="Lasting Performance" strain="2"  bookref="NG p.226"><BASE type="talent" minrank="9"  name="Performance"/>                               </KNACK>
	<KNACK name="Lay of the Land"     strain="1"  bookref="NG p.226"><BASE type="talent" minrank="5"  name="Lifesight"/>                                 </KNACK>
	<KNACK name="Locate Horror"       strain="4"  bookref="NG p.226"><BASE type="talent" minrank="7"  name="Bear Mark"/>                                 </KNACK>
	<KNACK name="Mind Reading"        strain="1"  bookref="NG p.227"><BASE type="talent" minrank="11" name="Lip Reading"/>                               </KNACK>
	<KNACK name="Mystic Mind Armor"   strain="2"  bookref="NG p.227"><BASE type="talent" minrank="8"  name="Mind Armor"/>                                </KNACK>
	<KNACK name="Scorn"               strain="2"  bookref="NG p.227"><BASE type="talent" minrank="7"  name="Performance"/>                               </KNACK>
	<KNACK name="Tail Sweep"          strain="2"  bookref="NG p.227"><BASE type="talent" minrank="9"  name="Unarmed Combat"/>                            </KNACK>
	<KNACK name="Threatening Aura"    strain="2"  bookref="NG p.227"><BASE type="talent" minrank="9"  name="Power Mask"/>                                </KNACK>
	<KNACK name="Treetrap"            strain="2"  bookref="NG p.227"><BASE type="talent" minrank="7"  name="Thread Weaving" limitation="Forest Weaving"/></KNACK>
	<KNACK name="Wind Shout"          strain="2"  bookref="NG p.227"><BASE type="talent" minrank="7"  name="Wind Dance"/>                                </KNACK>
	<KNACK name="Wood Wings"          strain="1"  bookref="NG p.227"><BASE type="talent" minrank="6"  name="Wood Skin"/>                                 </KNACK>
</KNACKS>
