=== SushySan/Earthdawn-Character-Editor/config/earthdawnpath.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/path" xmlns="http://earthdawn.com/path" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="PATHRANK_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTPERDAY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTESTSTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PATHTIER_type">
		<xs:annotation><xs:documentation>The path ranks are grouped by tiers</xs:documentation></xs:annotation>
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="15" name="RANK" type="PATHRANK_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="edt:tierkind_type" default="auto">
			<xs:annotation><xs:documentation>By default the tier kind is determinate automatically, starting with novice. At any point, it is possible to skip one tier kind and have the following tier kinds automatically be determinate again. The tier kind order must never be mixed. You must never use a lower tier kind after a higher tier kind. The order is: novice, journeyman, warden, master. The tier kind “auto” is always possible.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="PATH">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="NEEDEDKNACK" type="xs:string"><xs:annotation><xs:documentation>This knack must be learned to access this path.</xs:documentation></xs:annotation></xs:element>
				<xs:element minOccurs="1" maxOccurs="1" name="TALENT" type="edt:TALENTABILITY_type"/>
				<xs:element minOccurs="1" maxOccurs="4" name="TIER" type="PATHTIER_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED4"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Journeyman.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Journeyman" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Journeyman</NEEDEDKNACK>
	<TALENT name="Journeyman" tier="master"/><!-- learned talent with knack on Rank1. The max rank is 5. -->
	<TIER name="journeyman">
		<PATHFOREIGNTALENTS maxcircle="4"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
		</RANK>
	</TIER>
	<TIER>
		<PATHFOREIGNTALENTS maxcircle="8"/>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Morphism"/>
		<PATHFOREIGNTALENTS maxcircle="12"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Journeyman Karma Rituals expand the adeptâ€™s perspective beyond their Discipline and often show adaptability to their surroundings. The Karma Ritual of some Journeymen is never the same twice, each day reflecting a new perspective and a slight variation.</KARMARITUAL>
	<HALFMAGIC>No additional half magic for Journeyman.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Purifier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Purifier" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Purifier</NEEDEDKNACK>
	<TALENT name="Purifier" tier="journeyman"/><!-- learned talent with knack on Rank1. The max rank is 5. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Awareness"/>
		<OPTIONALTALENT name="Blood Share"/>
		<OPTIONALTALENT name="Cold Purify"/>
		<OPTIONALTALENT name="Earth Bond"/>
		<OPTIONALTALENT name="Elemental Hold"/>
		<OPTIONALTALENT name="Elemental Tongues"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="mystic"/>
		</RANK>
	</TIER>
	<TIER>
		<OPTIONALTALENT name="Lifesight"/>
		<OPTIONALTALENT name="Purification"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
		</RANK>
	</TIER>
	<KARMARITUAL>Purifiers’ Karma Rituals incorporate themes of healing, purification, or retribution against harm caused to the world.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Purifiers and know the history of Purifiers. Additionally, the adept can use Half-Magic to recognize environmental destruction caused by Horrors, Namegivers, and other “unnatural” causes, know how to preserve and restore destruction, and perform mundane preservation and restoration activities.</HALFMAGIC>
</PATH>

=== SushySan/Earthdawn-Character-Editor/config/paths/ED4en/Outcast.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<PATH name="Outcast" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/path" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/path ../../earthdawnpath.xsd">
	<NEEDEDKNACK>Outcast</NEEDEDKNACK>
	<TALENT name="Outcast " tier="journeyman"/><!-- learned talent with knack on Rank1. The max rank is 5. -->
	<TIER name="journeyman">
		<OPTIONALTALENT name="Battle Shout"/>
		<OPTIONALTALENT name="Danger Sense"/>
		<OPTIONALTALENT name="Fireblood"/>
		<OPTIONALTALENT name="Iron Constitution"/>
		<OPTIONALTALENT name="Rite of Kho’pesh"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<OPTIONALTALENT name="Wound Balance"/>
		<RANK><!-- 1 -->
			<TALENTABILITY/>
                </RANK>
		<RANK><!-- 2 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK>
		<RANK><!-- 3 -->
			<TALENTABILITY/>
		</RANK>
		<RANK><!-- 4 -->
			<TALENTABILITY/>
			<DEFENSE kind="social"/>
		</RANK> 
	</TIER>
        <TIER name="warden">
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Temper Flesh"/>
		<RANK><!-- 5 -->
			<TALENTABILITY/>
                </RANK>
	</TIER>
	<KARMARITUAL>Most Outcasts’ Karma Rituals do not change upon their Severing.</KARMARITUAL>
	<HALFMAGIC>The adept can also use their Half-Magic to find other Outcasts and know the history of Outcasts. Additionally, the adept can use Half-Magic to maintain and repair damage to their equipment, such as patching clothes, repairing a fishing net, or damage caused to their armor and weapons.</HALFMAGIC>	
</PATH>
